---
- name: Clone secrets repo
  git:
    accept_hostkey: true
    repo: "https://airsoftsweden:{{ lookup('ansible.builtin.env', 'GH_TOKEN') }}@github.com/airsoftsweden/taky-secrets.git"
    dest: /opt/taky-secrets
    version: "main"

#create folder
#copy certs to folder
- name: Copy secrets to destination
  copy:
    src: /opt/taky-secrets/data/ssl
    dest: /docker/data/taky-data
    mode: "0744"
    owner: 1000
    group: 1000