---
- name: Pull Taky image
  docker_image:
    name: skadakar/taky:latest
    source: pull

- name: Docker Compose Up Taky
  docker_compose:
    project_src: docker/
    files: 
      - docker-compose.yml

- name: Crontab - Restart Taky-CoT
  cron:
    name: Restart Taky-CoT
    user: root
    hour: 6
    job: "docker restart taky-cot"


- name: Crontab - Restart Taky-Data
  cron:
    name: Restart Taky-Data
    user: root
    hour: 6
    job: "docker restart taky-data"