---
- name: Install Certbot via Snap
  snap:
    name:
      - certbot
    classic: true

- name: Issue or Renew Certificate
  command:
    cmd: certbot certonly -n --standalone --agree-tos -d '{{ lookup('ansible.builtin.env', 'IP') }}' -m '{{ lookup('ansible.builtin.env', 'EMAIL') }}'
