---
- name: GH_TOKEN
  ansible.builtin.debug:
    msg: "{{ lookup('ansible.builtin.env', 'GH_TOKEN') }} is the github Token environment variable."

- name: Clone secrets repo
  git:
    accept_hostkey: true
    repo: "https://airsoftsweden:{{ lookup('ansible.builtin.env', 'GH_TOKEN') }}@github.com:airsoftsweden/taky-secrets.git"
    dest: /opt/taky-secrets
    version: "main"