---
- name: Create taky-mumble folder
  file:
    path: /docker/data/taky-mumble
    state: directory
    mode: '0755'

- name: Move Certs config to taky-mumble
  copy:
    src: /etc/letsencrypt/live/{{ lookup('ansible.builtin.env', 'IP') }}/{{ item }}
    dest: /docker/data/taky-mumble/{{ item }}
    mode: '0777'
  with_items:
    - fullchain.pem
    - privkey.pem

- name: Pull Mumble image
  docker_image:
    name: mumblevoip/mumble-server:latest
    source: pull

- name: Docker Compose Up Mumble
  community.docker.docker_compose_v2:
    project_src: docker/
    files: 
      - docker-compose-mumble.yml