---
- name: Clone secrets repo
  git:
    accept_hostkey: true
    repo: "https://airsoftsweden:{{ lookup('ansible.buildin.env', 'GH_TOKEN') }}@github.com:airsoftsweden/taky-secrets.git"
    dest: /opt/taky-secrets
    version: "main"