version: "3"
services:
  taky-rtsp:
    container_name: taky-rtsp
    image: aler9/rtsp-simple-server
    ports:
      - 1935:1935
      - 8554:8554
      - 8888:8888
      - 9997:9997
    environment:
      - RTSP_PROTOCOLS=tcp
    volumes:
      - /docker/data/taky-rtsp/rtsp-simple-server.yml:/rtsp-simple-server.yml:ro
    restart: unless-stopped

  taky-bordercar:
    container_name: taky-bordercar
    image: securitybits/taky-bordercar
    environment:
      - STREAM_URL=${IP}
      - CERT_PASS=${KEY_PW}
      - IP=${IP}
    volumes:
      - /docker/data/taky-data:/data
    restart: unless-stopped
    depends_on:
      - taky-rtsp